
ALTER TABLE MultipaymentMean ALTER COLUMN Amount DECIMAL(29, 11)
ALTER TABLE MultipaymentMean ALTER COLUMN Total DECIMAL(29, 11)
ALTER TABLE MultipaymentMean ALTER COLUMN OpenAmount DECIMAL(29, 11)
ALTER TABLE MultipaymentMean ALTER COLUMN SCRate DECIMAL(29, 11)
ALTER TABLE MultipaymentMean ALTER COLUMN LCRate DECIMAL(29, 11)