SET IDENTITY_INSERT [dbo].[Menu] ON 

INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Cente/General/Company', N'/Company/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Cente/General/Branch', N'/Branch/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Cente/General/Reciept', N'/ReceiptInformation/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Cente/General/User Account', N'/Account/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Cente/General/Printer Name', N'/PrinterName/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Financails/ChartOfAccount', N'/ChartOfAccounts/Detail')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Finalcails/Journal Entry', N'/Financials/JournalEntry')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Finalcails/FinancailsReport/Balance Sheet', N'/FinancialReports/BalanceSheet')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Finalcails/FinancailsReport/Profit Adn Lost', N'/FinancialReports/ProfitAndLost')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Finalcails/FinancailsReport/Cash Flow for Treasury', N'/FinancialReports/CashFlowForTreasury')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Finalcails/FinancailsReport/Trail Balnce', N'/FinancialReports/TrialBalance')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Finalcails/FinancailsReport/Sale Grose Profit', N'/FinancialReports/SaleGrossProfit')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Inventory/Proerty', N'/Property/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Table/Table', N'/Table/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Table/Table Group', N'/GroupTable/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Set/General/Freight', N'/Freight/index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Set/General/Seting Dashbaord', N'/SettingDashboard/DashboardPrivileges')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Set/General/General seting', N'/GeneralSettingAdmin/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Set/General/Service', N'/ServiceAlertSetup/ServiceAlert')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Set/General/Remark Discount', N'/RemarkDiscount/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Setup/Financial/G/L Account Dtermimation', N'/GLAccountDetermination/GLAccounting')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/Setup/Financial/Tax Group', N'/TaxGroup/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/System Initialization/Period Indicator', N'/PeriodIndicator/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/System Initialization/Posting Periods', N'/postingperiod/index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Control Center/System Initialization/Document Numbering', N'/DocNumbering/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'POS/KRMS', N'/POS/KRMS')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'POS/KTMS', N'/POS/KTMS')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'POS/KBMS', N'/POS/KBMS')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'POS/KSMS', N'/POS/KBMS')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R Quotation', N'/Sale/SaleQuote')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R/Sale Order', N'/Sale/SaleOrder')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R/Sale Selivery', N'/Sale/SaleDelivery')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R/Return Delivery', N'/Sale/ReturnDelivery')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R/ A/R Down Payment', N'/Sale/ARDownPaymentInvoice')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R/ A/R Invoice', N'/Sale/SaleAR')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Sale A/R/ A/R Credit Memo', N'/Sale/SaleCreditMemo')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P /Purchase Order', N'/PurchaseOrder/Purchaseorder')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P / Goods Receipt PO', N'/PurchasePO/PurchasePO')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P / AP Invoice', N'/PurchaseAP/PurchaseAP')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P / AP Credit Memo', N'/PurchaseCreditMemo/PurchaseCreditMemo')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Itemmasterdata', N'/ItemMasterData/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Price List', N'/PriceList/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Print Barcode/Barcode A4', N'/Printbarcode/Barcodelayout')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Print Barcode/Label Barcode ', N'/BarcodeToService/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Label scale/Scale Rongta', N'/LabelScale/LabelScale')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Label scale/Scale CAS', N'/LabelScale/LabelScaleCAS')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Item Management/Item Serial Number/ Serial Number Managerment', N'/ItemSerialNumbers/SerialNumberManagement')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Item Management/Item Serial Number/ Serial Number Details', N'/ItemSerialNumbers/SerialNumberDetails')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Item Management/Batch/Batch Managerment', N'/ItemBatchNo/BatchManagement')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Item Management/Batch/Batch Details', N'/ItemBatchNo/BatchDetails')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Transaction/Goods Receipts', N'/GoodsReceipt/GoodsReceipt')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Transaction/Goods Issue', N'/GoodIssues/GoodIssues')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Inventory/Transaction/Transfer', N'0/Transfer/Transfer')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'KSMS/SetUp Service', N'/ksmsservicesetup/setup')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Customer', N'/BusinessPartner/Customer')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Vendor', N'/BusinessPartner/Vendor')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Report Customer Aging', N'/BPAging/CustomerAging')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Report/Vendor Aging', N'/BPAging/VendorAging')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Card Member/Cards', N'/CardMember/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Card Member/type Card', N'/CardMember/CardTypeIndex')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Business Partner/Card Member/Deposit', N'/CardMember/DepositCardMember')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P /Purchase Request', N'/PurchaseRequest/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P /Purchase Quotation', N'/PurchaseQuotation/Index')
INSERT [dbo].[Menu] ([Title], [Url]) VALUES (N'Purchasing A/P /AP Reserve Invoice', N'/PurchaseAP/Index')
SET IDENTITY_INSERT [dbo].[Menu] OFF
